### ISSUE TITLE
点击和显示位置偏移

### ISSUE THREAD

**Issue by david082321** [twoyi/twoyi#11]
1. 我长按图中红点的位置，点的却是下面的项目
![Screenshot_20220104-020433_twoyi](https://user-images.githubusercontent.com/7046617/147964347-71cbf1bb-b964-41c0-91be-1ac7039e8bd0.png)

2. 将两仪移到后台，然后再返回，位置正常了
![Screenshot_20220104-020456_twoyi](https://user-images.githubusercontent.com/7046617/147964504-c66a56eb-7958-4aeb-8386-8cec6bd9ddd5.png)

3. 重启两仪又会出现相同的问题

系统 Android 11
型号 三星SM-A528B

**Comment by sertwen** [comment]
A10 Lineage 小米Mix2s 一样

**Comment by tiann** [comment]
虚拟导航栏存在时有此问题

**Comment by tiann** [comment]
0.3.4 已修复虚拟导航栏问题。
