### ISSUE TITLE
Several bugs and issues

### ISSUE THREAD

**Issue by josefv2** [twoyi/twoyi#116]
After needing an VM to contain proprietary chats I have no choice but to use, I found some bugs on twoyi that makes it less practical to use than it should be. It would be nice if you could work on them.

1 - This app randomly crashes with no cause or warning, sometimes as soon as it boots, sometimes can take minutes.

2 - Video, audio and GIFs on chats (seen in WhatApp) are not visible: audio is silent, video and GIFs are nothing but black screens displaying nothing.

3 - As seen previously, it's OK to send logs as long as trackers are reputable and trustworthy, this isn't the case for Microsoft: https://github.com/twoyi/twoyi/issues/76#issuecomment-1100684050
Replacing them with a privacy friendly alternative would be amazing to have.

**Comment by KyleSteve07** [comment]
Im with you here too

Yes, It is Randomly Crash/ Always Crashing

**Comment by tiann** [comment]
Please send me the bugreport: Setting -> Send Log and open a new issue.
