### ISSUE TITLE
app launch fail.

### ISSUE THREAD

**Issue by dengdengwa** [twoyi/twoyi#118]
crash log:
E/zygote64: Unable to stat fd 9: Permission denied
E/zygote64: Unsupported AF_UNIX socket (fd=36) with abstract address.

**Comment by dengdengwa** [comment]
Android 10, pixel 2

**Comment by tiann** [comment]
使用 两仪设置-发送日志  不要发你觉得有用的日志。

**Comment by tiann** [comment]
Please try 0.7.1: https://coolapk.com/apk/io.twoyi
