### ISSUE TITLE
屏幕滑动就会震颤问题

### ISSUE THREAD

**Issue by Firemime** [twoyi/twoyi#120]
bugreport（系统日志）, 下载链接:https://wwp.lanzoup.com/iMJG708c022f  ,提取码 :4554
bug的录屏(解压看), 下载链接:https://wwp.lanzoup.com/i6ZKP08c04di  提取码 :4554
鸿蒙2.0系统

**Comment by lincannm** [comment]
一样的问题，只要是动画就会鬼畜抖动，好像当前帧突然又回到了前几帧这样子
Redmi k30 4g, miui12.5.6, android11

**Comment by liuliang520500** [comment]
一样的，鸿蒙2.0，屏幕颤抖，应用进不去

**Comment by tiann** [comment]
GPU 直通已修复，请尝试 0.7.1 版本。

**Comment by amu1680c** [comment]
gpu直通以后还是有这个问题，第一次打开会震颤，管理器重启一次就不震颤了
