### ISSUE TITLE
Add TWRP as custom recovery 

### ISSUE THREAD

**Issue by kairusds** [twoyi/twoyi#125]
Is it possible to have the custom recovery be TWRP?

**Comment by tiann** [comment]
There isn't any recovery in twoyi... And it is not necessary because the system directory is always writable, we can just replace it with the factory ROM

**Comment by kairusds** [comment]
> There isn't any recovery in twoyi... And it is not necessary because the system directory is always writable, we can just replace it with the factory ROM

oh alright
