### ISSUE TITLE
语言bug

### ISSUE THREAD

**Issue by qi-mooo** [twoyi/twoyi#15]
设置语言为粤语必定卡死，
![Screenshot_2022-01-04-03-02-15-33_41e8f3d7b2e3c54bc98b1507aeaff91e](https://user-images.githubusercontent.com/59095213/147969488-72464060-4866-4545-bbc6-b9138de06190.jpg)

**Comment by PollexLee** [comment]
设置中文，也卡死了。

**Comment by yuwuwei** [comment]
设置完关掉两仪重新进入就好了，我设置了粤语没问题，就是没显示什么粤语内容，现在的版本切换语言都要卡一下

**Comment by tiann** [comment]
#1
