### ISSUE TITLE
首次启动时出现未安装的应用图标

### ISSUE THREAD

**Issue by MlgmXyysd** [twoyi/twoyi#22]
AOSP键盘
等待一段时间后消失
![Screenshot_20220104-153421](https://user-images.githubusercontent.com/17919858/148025253-f2dd72db-a9ca-40e5-a082-d95db3323cb0.jpg)

**Comment by yuwuwei** [comment]
这是已安装的，只不过后面隐藏了，可以去设置键盘那里勾选显示应用图标来显示

**Comment by tiann** [comment]
0.2.4 已修复！
