### ISSUE TITLE
黑屏卡死

### ISSUE THREAD

**Issue by wahowe** [twoyi/twoyi#25]
测试环境：OPPO Reno 安卓10
已安装magisk,LSPosed
问题反馈:
1.两仪安装后居然申请root权限，赋予后飞码刷屏
2.在两仪内，导入文件选取+采取外部安装方式，选取文件后，提示解析包错误，无法安装
3.内部时间无法更改修正
4.内部开发者选项，点击后黑屏卡死
5.建议内部桌面背景更改一下，以区别VirtualXposed,感觉一样风格背景
...

**Comment by tiann** [comment]
#4
