### ISSUE TITLE
两仪中不能登陆微信

### ISSUE THREAD

**Issue by shiyanaaa** [twoyi/twoyi#28]
两仪中不能登陆微信，打开一些第三方app黑屏，卡死

**Comment by tiann** [comment]
不能登录微信具体情况是什么？

**Comment by shiyanaaa** [comment]
> 不能登录微信具体情况是什么？

选择验证码登录，发送验证码无法发出，也不显示发送成功，选择密码登录一直显示正在登陆中
还有就是桌面经常黑屏卡死，什么都没有操作，
app运行经常卡死

**Comment by tiann** [comment]
0.2.4 版本是否存在此问题？

**Comment by shiyanaaa** [comment]
> 0.2.4 版本是否存在此问题？

 没有问题了
