### ISSUE TITLE
无法卸载QQ，一点应用管理的QQ，就界面卡死不动

### ISSUE THREAD

**Issue by wahowe** [twoyi/twoyi#29]
测试环境：OPPO RENO 安卓10
已magisk和LSPosed
问题：无法卸载QQ8.8.38，一点应用管理的QQ就界面卡死不动，只能强制关闭两仪

**Comment by tiann** [comment]
c

**Comment by tiann** [comment]
0.2.4 版本是否存在此问题？

**Comment by tiann** [comment]
0.3.5 应该已修复此问题。
