### ISSUE TITLE
一加9p 0.1.6版本，打开后直接崩

### ISSUE THREAD

**Issue by JiZhi-Error** [twoyi/twoyi#30]
![image](https://user-images.githubusercontent.com/24365406/148309037-f073e5d6-8916-497e-9fd4-832d04ff2501.png)

**Comment by tiann** [comment]
清除数据重新打开试试

**Comment by JiZhi-Error** [comment]
> 清除数据重新打开试试

我卸载重装的

**Comment by JiZhi-Error** [comment]
最新版本清楚数据可以直接打开

**Comment by JiZhi-Error** [comment]
最新版已修好
