### ISSUE TITLE
[0.1.8]卡顿/闪退/应用消失问题

### ISSUE THREAD

**Issue by KyuubiRan** [twoyi/twoyi#35]
【设备信息】Mi 9 / MIUI 12.5.4 (Android 11)
【复现方式】第一次打开后直接点两仪设置，退出来之后会使键盘设置应用消失，并且再点开设置就回闪退回锁屏界面，再次解锁点击app会变得很卡，此时两仪设置会打不开，打开其他应用会疯狂闪屏并且巨卡无比。

**Comment by KyuubiRan** [comment]
此现象在0.1.7版本同样可以复现

**Comment by tiann** [comment]
请尝试 0.2.4 版本

**Comment by KyuubiRan** [comment]
> 请尝试 0.2.4 版本

0.2.4版本设置的问题是修好了，但是点开两仪设置再点开文件管理之后会彻底卡死，杀死app再重新启动也会直接卡死，只能清除数据恢复正常

**Comment by KyuubiRan** [comment]
看样子0.2.4没有问题了
