### ISSUE TITLE
启动特效与软件内系统界面重叠并疯狂闪烁

### ISSUE THREAD

**Issue by 2yiuser** [twoyi/twoyi#39]

**Comment by 2yiuser** [comment]
![Uploading Screenshot_2022-01-07-20-53-39-945_io.twoyi.jpg…]()

**Comment by tiann** [comment]
两仪什么版本？

**Comment by EscapeA** [comment]
> 

0.3.5仍然有概率出现，忘截图了，出现前进行了一次所有数据，初始化后进入桌面特效叠加层依然显示，不影响操作（能正常操作两以内系统），大约10秒左右两仪**闪退**，不复现（

**Comment by tiann** [comment]
#78
