### ISSUE TITLE
魅族17Pro使用问题

### ISSUE THREAD

**Issue by sunowsir** [twoyi/twoyi#42]
0.19版本还是无法导入应用![S20108-16415809.png](https://user-images.githubusercontent.com/30584006/148637968-3d8c4bf3-57f9-490f-89da-c8eb02834a09.png)

**Comment by tiann** [comment]
我找了个 魅族17Pro试了下，0.3.5 版本可以正常导入；如果有问题，请尝试卸载后重装。

**Comment by sunowsir** [comment]
依然有该问题

**Comment by sunowsir** [comment]
还是这样，算了，我放弃了
