### ISSUE TITLE
0.2.2直接卡死

### ISSUE THREAD

**Issue by XMWML** [twoyi/twoyi#43]
一进去初始化完毕就卡在壁纸那里
两仪版本：0.2.2
安卓版本：11
机型：小米8
![Screenshot_20220112-073146_twoyi](https://user-images.githubusercontent.com/97565793/149037708-fb6f41cb-9a57-410e-8714-ac67ba2cfa92.png)

**Comment by FreeDreamWings** [comment]
卡在这个界面疯狂点击屏幕，然后闪退了再打开就可以了。。。。。。

**Comment by tiann** [comment]
0.2.4 已修复！
