### ISSUE TITLE
[rust编译失败解决方案]

### ISSUE THREAD

**Issue by hhhaiai** [twoyi/twoyi#47]
# cargo编译失败及结局办法

## 1. 平台
mac m1, 12.0.1 

## 2. 软件环境

* cargo版本

    ``` 
    > cargo -V
    cargo 1.58.0 (f01b232bc 2022-01-19)
    ```

## 3. 编译问题及解决办法

* 3.1. `cargo ndk`错误

    - 解决办法: 手动下载git库[cargo-ndk](https://github.com/tiann/cargo-ndk) 到`.cargo/registry/src/github.com-*****/cargo-ndk-2.5.0`  (****为自动生成目录)
    - 原因: 国内网络+cargo索引失败导致下载失败
* 3.2.  can't find crate for `std` / can't find crate for `core`
    - 日志提示: `rustup target add armv7-linux-androideabi`
    - 根据平台修改: `rustup target add arm-linux-androideabi` / `rustup target add  aarch64-linux-android`
    - 官方库: https://static.rust-lang.org/dist/2022-01-20/ ，搜索 `linux-androideabi`

* 3.3.  `aarch64-linux-android21-clang` not found
    - 解决办法: `local.properties`文件中增加`ndk.dir=sdk/ndk/22.0.7026061`
    - 环境变量也修改下: 本地修改几个变量`NDK_HOME`/`ANDROID_NDK_ROOT`/`ANDROID_NDK_HOME`
`

**Comment by qdsfdhvh** [comment]
编译的时候遇到这个报错`error: unable to find library -lOpenglRender`，这个如何解决
```shell
[2022-02-09T08:28:40Z INFO  cargo_ndk::cli] Using NDK at path: /Users/seiko/Library/Android/sdk/ndk/22.0.7026061
[2022-02-09T08:28:40Z INFO  cargo_ndk::cli] NDK API level: 21
[2022-02-09T08:28:40Z INFO  cargo_ndk::cli] Building targets: arm64-v8a
[2022-02-09T08:28:40Z INFO  cargo_ndk::cli] Building arm64-v8a (aarch64-linux-android)
   Compiling twoyi v0.1.0 (/Users/seiko/Developer/Android/Seiko/twoyi/app/rs)

error: linking with `/Users/seiko/Library/Android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang` failed: exit status: 1
  |
  = note: "/Users/seiko/Library/A....
.....
.....
/Android/Seiko/twoyi/app/rs/target/aarch64-linux-android/debug/deps/libtwoyi.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: ld: error: unable to find library -lOpenglRender
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `twoyi` due to previous error
[2022-02-09T08:28:43Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2022-02-09T08:28:43Z INFO  cargo_ndk::cli] 
[2022-02-09T08:28:43Z INFO  cargo_ndk::cli]     rustup target install aarch64-linux-android

```

**Comment by tiann** [comment]
用 build_rs.sh 这个脚本编译

**Comment by tiann** [comment]
cargo 依赖安装不上的话，推荐使用代理而不是自己去下载，代理配置方法：[Rust Crate.io的国内代理](https://www.jianshu.com/p/3e52eb22a0a3)

**Comment by qdsfdhvh** [comment]
> 用 build_rs.sh 这个脚本编译

成功了，谢谢大佬ღ( ´･ᴗ･` )

**Comment by hhhaiai** [comment]
* 目录app/rs下，执行编译脚本: bash  build_rs.sh  --release
* 如异常：可尝试cargo ndk build
* 如还异常: 可尝试cargo build
