### ISSUE TITLE
BUG 无法扫描到wifi 

### ISSUE THREAD

**Issue by flyxinhua** [twoyi/twoyi#48]
手机：华为mate 20 ,系统：鸿蒙2.0.0，应用：两仪0.3.5 
尝试过开关，和重启，恢复网络设置。和物理机的开关。
均无法扫描到wifi。

**Comment by flyxinhua** [comment]
在桌面也有概率闪屏。

**Comment by tiann** [comment]
非 bug，预期行为。

**Comment by flyxinhua** [comment]
那是否认为无法安装必须联网的应用？

**Comment by tiann** [comment]
无法扫描到wifi不影响网络使用
