### ISSUE TITLE
通过安装包导入应用时报错

### ISSUE THREAD

**Issue by tangjihe0** [twoyi/twoyi#49]
非常感谢开发出两仪并开源。
![微信截图_20220209155825](https://user-images.githubusercontent.com/39062484/153146934-bf29edc5-3161-4a4e-903d-839301439113.png)
如图，在导入应用中点加号选中apk文件是报错。并且冷启动第一次会闪退，第二次才能进入桌面。
机型：真我GT Neo 闪速版（RMX3350）
安卓版本：11
固件版本：RMX3350_11_A.16
还有现在安卓11不root无法直接访问data文件夹，容器想和本机互传数据比较麻烦。

**Comment by tiann** [comment]
安装包是 32 位的吗？

**Comment by tiann** [comment]
037 已修复 安装失败的问题。
