### ISSUE TITLE
ROM什么时候开源

### ISSUE THREAD

**Issue by Ahackerl** [twoyi/twoyi#53]
ROM什么时候开源

**Comment by tiann** [comment]
业余维护，无法给出一个确切的时间点。

**Comment by Ahackerl** [comment]
> 业余维护，无法给出一个确切的时间点。

能不能先出一个版本，对这个特别感兴趣

**Comment by tiann** [comment]
ROM 里面的代码涉及到两年多断断续续的各种修改，整个 repo 下有很多仓库都有改动；直接放出来根本没法看。

**Comment by crazyn2** [comment]
可以放出来一起看
