### ISSUE TITLE
在Android Studio编译不通过

### ISSUE THREAD

**Issue by Ahackerl** [twoyi/twoyi#59]
配置好cargo xdk so库在命令行编译成功，在安卓studio报错：Process 'command 'sh'' finished with non-zero exit value 127

**Comment by Ahackerl** [comment]
android studio重启即可 xdk环境变量没有更新。

**Comment by janus-xiao** [comment]
Caused by: java.io.IOException: Cannot run program "sh" (in directory "E:\AS_Work\Github\twoyi-main\app\rs"): CreateProcess error=2
我跟你一样的情况，命令行能便宜，AS跑不起来，重启了也没用。。

**Comment by janus-xiao** [comment]
cargo ndk 需要单独配置环境变量吗？我现在配置了Android ndk 的环境变量
