### ISSUE TITLE
安装太极提示需要更新模块引擎

### ISSUE THREAD

**Issue by dapao035** [twoyi/twoyi#63]
太极提示需要更新模块引擎，然后提示无网络连接，无法更新
![Screenshot_2022-02-12-13-30-18-244_io twoyi](https://user-images.githubusercontent.com/18631966/153704561-db5fa936-9944-4e16-b342-77ad2989a766.jpg)
![Screenshot_2022-02-12-16-50-42-922_io twoyi](https://user-images.githubusercontent.com/18631966/153704573-af90ffa2-b044-4d98-a4b7-850752d13965.jpg)

**Comment by dapao035** [comment]
钉钉提示没有网络连接

**Comment by teble** [comment]
请进入设置，wifi选择twoyi进行连接，默认没有联网

**Comment by tiann** [comment]
先连接 wifi 后再试。

**Comment by js2854** [comment]
0.4.1的两仪也遇到这个问题，手机是红米note8 pro。两仪中浏览器联网正常，设置中wifi无法连接twoyi，因为扫描不到这个接入点，已保存的网络中倒是有twoyi。
