### ISSUE TITLE
/system/bin/sh : su : Operation not permitted

### ISSUE THREAD

**Issue by zairullahdev** [twoyi/twoyi#65]
你好，我来自印度尼西亚，我想问超级用户是错误的，它总是说不允许操作

**Comment by zairullahdev** [comment]
![Uploading Screenshot_20220214_141413.jpg…]()

**Comment by zairullahdev** [comment]
![Screenshot_20220214_141413](https://user-images.githubusercontent.com/99532718/153817014-486b3f37-4064-4362-9d1e-f0f04a371660.jpg)

**Comment by canyie** [comment]
Are you using a Vivo device?

**Comment by zairullahdev** [comment]
Yes

**Comment by canyie** [comment]
Vivo's kernel restriction, see topjohnwu/Magisk#5148

**Comment by zairullahdev** [comment]
There Emulator Named VPhoneGaGa, Using Android 7, And not being Restricted using su, because it's has it own zygote to start the own directory of the emulator, the developer should add this feature

**Comment by tiann** [comment]
should be fixed in: https://github.com/twoyi/Superuser/commit/416660aaa94e8d963c98d6bbcd0296dff216775d
