### ISSUE TITLE
另一种boot timeout情况

### ISSUE THREAD

**Issue by EscapeA** [twoyi/twoyi#73]
当时忘了保存一份日志了,清除了全部数据,后面又没有复现,
日志重复一句

```
02-19 14:52:21.888 23851 23851 E vbinder : binder ioctl recv err: 0, cmd: BINDER_WRITE_READ, errno: 32(Broken pipe)
```
![Screenshot_2022-02-19-14-53-49-448_bin.mt.plus.jpg](https://user-images.githubusercontent.com/53213938/154792004-d2b1d496-0908-4d69-b419-04a1aa4541b6.jpg)

**Comment by tiann** [comment]
这种属于进程被杀了，请提供详细日志。
