### ISSUE TITLE
Privacy concern

### ISSUE THREAD

**Issue by josefv2** [twoyi/twoyi#76]
Launched this app with TrackerControl and immediately detected 2 trackers in your app: Microsoft Visual Studio Analytics and Crashes. Those are owned by Microsoft, so they should be a big privacy concern if they can access anywhere near my device. Why are them included? Why even needed?

Can I ask exactly **what is collected** when I use this app?

**Comment by tiann** [comment]
please read the source code.

**Comment by josefv2** [comment]
> please read the source code.

I cannot read code. I'm only an user who wanted privacy and stumbled upon Microsoft Data collection!!! I have no code knowledge, sorry, don't know to read code. I still wonder why it's included on this and what does it see... please!

**Comment by tiann** [comment]
AppCenter is used to collect logcat to help fixing boot failure issue for twoyi, here it the source code: https://github.com/twoyi/twoyi/blob/main/app/src/main/java/io/twoyi/utils/LogEvents.java#L45

When twoyi boot failed, it will collect `logcat`, `tombstone`, `dmesg` and `dropbox` in twoyi(not the host system outside) and upload it to AppCenter, it doesn't contain any personal information, only upload phone model, Android version.

Anyway, i need the log to improve twoyi, if you don't like it or don't trust what i said, feel free to uninstall it.

**Comment by josefv2** [comment]
The issue is not that twoyi tracks activity, rather, what it's used to do it does.
Twoyi is meant to only collect crash data. However, I used TrackerControl to see activity and Microsoft trackers are reported to collect **even on successful boots.**

So, the app may not collect info outside crashes but Microsoft likely does, it may go independently. Again it sends activity constantly every 20 seconds or so.

**Comment by josefv2** [comment]
> AppCenter is used to collect logcat to help fixing boot failure issue for twoyi, here it the source code: https://github.com/twoyi/twoyi/blob/main/app/src/main/java/io/twoyi/utils/LogEvents.java#L45
> 
> When twoyi boot failed, it will collect `logcat`, `tombstone`, `dmesg` and `dropbox` in twoyi(not the host system outside) and upload it to AppCenter, it doesn't contain any personal information, only upload phone model, Android version.
> 
> Anyway, i need the log to improve twoyi, if you don't like it or don't trust what i said, feel free to uninstall it.

After another test I would like to do another question.

Twoyi itself has been proven to not track, the code is there and collects nothing personal. However, the tracking component seems to act on it's own, and it's like twoyi had no control over it.

While twoyi is transparent, Microsoft analytics itself shown behavior different from both the code and what it's said:

1 - it sends info every 30 seconds
2 - it's active even on successful boots
3 - the destination location matches Microsoft location

Tested from TrackerControl which detected this **on successful boots, while never crashing**. This shouldn't happen seeing the code. It's a Microsoft concern, not on the twoyi project but it would look like the tracker acts completely independently from the app. Is this intended and the uncrashed checks simply contain empty data or the tracker is external to twoyi code? Because again it's not twoyi telemetry but acts like Microsoft would.

**Comment by tiann** [comment]
I think you should report it to Microsoft.
