### ISSUE TITLE
小米Mix4 MIUI13无法导入应用

### ISSUE THREAD

**Issue by PikachuCN** [twoyi/twoyi#8]
导入后会报错，然后直接卡死。重启后，应用也不存在，我导入的是Via。
偶发性滑动时会卡死，然后直接需要强制结束应用

![](https://s2.loli.net/2022/01/04/CNkxrGmiAPTjopw.jpg)
![](https://s2.loli.net/2022/01/04/Tyi8xlF35mNqYfd.jpg)

**Comment by PollexLee** [comment]
一样的现象，小米10，miui12.5，重启手机，重启两仪，又从主设备安装了一次，正常了。

**Comment by tiann** [comment]
0.1.8 已修复。
