### ISSUE TITLE
[Android8.0.0]将要进入系统界面时闪退

### ISSUE THREAD

**Issue by KJZH001** [twoyi/twoyi#87]
## 问题描述
因为我当前的安卓设备为8.0.0，所以我尝试通过修改apk降低版本要求来让两仪在我的设备上运行起来

由于这低于了您所设置的最低要求的系统版本8.1.0，我不清楚这种issue您是否会受理，对此我表示抱歉

当前两仪版本：0.3.5（当前Github发行版中的最新构建）

闪退是大约在最后一张图左右的位置发生的

如果需要更加详细的log，请在下方留言并且请麻烦告诉我如何能够拿到更加详细的log
## 预览截图
[![JIFi.jpg](https://img.cdn.loliloli.net/images/2022/03/04/JIFi.jpg)](https://img.loliloli.moe/image/JIFi)
[![JZUZ.jpg](https://img.cdn.loliloli.net/images/2022/03/04/JZUZ.jpg)](https://img.loliloli.moe/image/JZUZ)
[![JX4f.jpg](https://img.cdn.loliloli.net/images/2022/03/04/JX4f.jpg)](https://img.loliloli.moe/image/JX4f)
[![JMzp.jpg](https://img.cdn.loliloli.net/images/2022/03/04/JMzp.jpg)](https://img.loliloli.moe/image/JMzp)

**Comment by tiann** [comment]
不支持 8.1 以下，改 minSdkVersion 没用。
