### ISSUE TITLE
App not installed 

### ISSUE THREAD

**Issue by Raif1** [twoyi/twoyi#93]
I recently opened the same issue but was closed ror some reason so im gonna do again and it seems like the app aint compatible with my device ![Screenshot_20220310-113238_App_Manager_1.png](https://user-images.githubusercontent.com/93464125/157596279-49dfe175-b5f5-4897-8986-ace3f789c746.png)

**Comment by tiann** [comment]
twoyi doesn't support 32bit devices and x86 devices.

**Comment by Raif1** [comment]
Ok

**Comment by Raif1** [comment]
Any plans for support?

**Comment by tiann** [comment]
No plan, Because 32-bit applications are about to exit the stage of history
