### ISSUE TITLE
Twoyi 0.5.1 issues

### ISSUE THREAD

**Issue by NSTAdventure** [twoyi/twoyi#94]
twoyi 0.5.1 have some issues
1. wifi isn't available
- wifi will always end up in ? mark if turned on
if you check wifi list on the setting it will always stuck on searching state
2. twoyi still unstable for running app:
- app will make twoyi freeze at least in my case

3. root isn't stable yet:
- you can't open supersu app
- you can't grant / revoke su permission if root app requesting root it will automatically granted
- app will request root / stop working on root mode if i left the app on background

4. twoyi isn't support 32 bit apps on me this is can lead to some problem because not all app is 64 bit especially taichi

**Comment by HuskyDG** [comment]
Twoyi will never support 32bit

**Comment by NSTAdventure** [comment]
> Twoyi will never support 32bit

bruh taichi is 32 bit that's the problem then how user can use taichi on this app?

btw pls don't close this issues because it's not only about 32 bit issues but many issues pls check the list thanks 🙏

**Comment by HuskyDG** [comment]
> > Twoyi will never support 32bit
> 
> bruh taichi is 32 bit that's the problem then how user can use taichi on this app?
> 
> btw pls don't close this issues because it's not only about 32 bit issues but many issues pls check the list thanks 🙏

https://taichi.cool/download.html

**Comment by HuskyDG** [comment]
It will be closed soon :)))

**Comment by NSTAdventure** [comment]
> It will be closed soon :)))

wait! 🙁🤦

**Comment by tiann** [comment]
Please attach the log and report issue separately. This doesn't help for fixing the issues.

**Comment by NSTAdventure** [comment]
> Please attach the log and report issue separately. This doesn't help for fixing the issues.

bruh how i can send log? I didn't see that feature anywhere i use 0.5.1 now

**Comment by tiann** [comment]
Settings - send log

**Comment by NSTAdventure** [comment]
> Settings - send log

done pls considering re open the issues if the problem isn't solved yet

i also send them to discussion group undername NST_Adventure
