### ISSUE TITLE
安装后虚拟机内部无法访问网络？这个要怎么设置吗

### ISSUE THREAD

**Issue by tbkuashidai** [twoyi/twoyi#99]

**Comment by zairullahdev** [comment]
尝试连接到内部 vm wifi (twoyi)

**Comment by bingying2** [comment]
遇到同样的问题，折腾好一会没解决，最后想着重启物理机一次试试不行就算了，结果好了...

**Comment by gitlikang** [comment]
荣耀手机+鸿蒙2.0也是重启物理机就好了……

**Comment by tiann** [comment]
Fixed in 0.7.0 https://coolapk.com/apk/io.twoyi
